imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    config:
        contentsCss: ["EXT:theme_bootstrap4/Resources/Public/Extensions/RteCkeditor/Stylesheets/default.css", "EXT:theme_bootstrap4/Resources/Public/Extensions/RteCkeditor/Stylesheets/theme.css"]

        stylesSet:
            # Block level styles

            # Responsive text alignment
#            - { name: "Text SM Left", element: "p", attributes: { 'class': 'text-sm-left' } }
#            - { name: "Text SM center", element: "p", attributes: { 'class': 'text-sm-center' } }
#            - { name: "Text SM right", element: "p", attributes: { 'class': 'text-sm-right' } }
#
#            - { name: "Text MD Left", element: "p", attributes: { 'class': 'text-md-left' } }
#            - { name: "Text MD center", element: "p", attributes: { 'class': 'text-md-center' } }
#            - { name: "Text MD right", element: "p", attributes: { 'class': 'text-md-right' } }
#
#            - { name: "Text LG Left", element: "p", attributes: { 'class': 'text-lg-left' } }
#            - { name: "Text LG center", element: "p", attributes: { 'class': 'text-lg-center' } }
#            - { name: "Text LG right", element: "p", attributes: { 'class': 'text-lg-right' } }
#
#            - { name: "Text XL Left", element: "p", attributes: { 'class': 'text-xl-left' } }
#            - { name: "Text XL center", element: "p", attributes: { 'class': 'text-xl-center' } }
#            - { name: "Text XL right", element: "p", attributes: { 'class': 'text-xl-right' } }

            # Text transform
            - { name: "Lowercased text", element: "p", attributes: { 'class': 'text-lowercase' } }
            - { name: "Uppercased text", element: "p", attributes: { 'class': 'text-uppercase' } }
            - { name: "CapiTaliZed text", element: "p", attributes: { 'class': 'text-capitalize' } }

            # Font weight and italics
            - { name: "Bold text", element: "p", attributes: { 'class': 'font-weight-bold' } }
            - { name: "Normal text", element: "p", attributes: { 'class': 'font-weight-normal' } }
            - { name: "Italic text", element: "p", attributes: { 'class': 'font-italic' } }



            - { name: "Lead", element: "p", attributes: { 'class': 'lead' } }

            # Inline styles
            - { name: "Primary Color", element: "span", attributes: { 'class': 'text-primary' } }

            # List styles
            - { name: "List unstyled", element: "ul", attributes: { 'class': 'list-unstyled' }, styles: { 'display': 'none' } }

            # Link styles
            - { name: "Button Default", element: "a", attributes: { 'class': 'btn btn-default' } }
            - { name: "Button Primary", element: "a", attributes: { 'class': 'btn btn-primary' } }
            - { name: "Button Success", element: "a", attributes: { 'class': 'btn btn-success' } }
            - { name: "Button Info", element: "a", attributes: { 'class': 'btn btn-info' } }
            - { name: "Button Warning", element: "a", attributes: { 'class': 'btn btn-warning' } }
            - { name: "Button Danger", element: "a", attributes: { 'class': 'btn btn-danger' } }

            # Table styles
            - { name: "Table", element: "table", attributes: { 'class': 'table table-hover' } }
            - { name: "Table Striped", element: "table", attributes: { 'class': 'table table-hover table-striped' } }
            - { name: "Table Bordered", element: "table", attributes: { 'class': 'table table-hover table-bordered' } }
            - { name: "Table Condensed", element: "table", attributes: { 'class': 'table table-hover table-condensed' } }
            - { name: "Row Active", element: "tr", attributes: { 'class': 'active' } }
            - { name: "Row Success", element: "tr", attributes: { 'class': 'success' } }
            - { name: "Row Info", element: "tr", attributes: { 'class': 'info' } }
            - { name: "Row Warning", element: "tr", attributes: { 'class': 'warning' } }
            - { name: "Row Danger", element: "tr", attributes: { 'class': 'danger' } }

        toolbarGroups:
            - { name: styles, groups: [ format, styles ] }
            - { name: basicstyles, groups: [ basicstyles ] }
            - { name: paragraph, groups: [ list, indent, blocks, align ] }
            - "/"
            - { name: links, groups: [ links ] }
            - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
            - { name: editing, groups: [ spellchecker ] }
            - { name: insert, groups: [ insert ] }
            - { name: tools, groups: [ table, specialchar ] }
            - { name: document, groups: [ mode ] }

        format_tags: "p;h1;h2;h3;h4;h5;pre"

        justifyClasses:
            - text-left
            - text-center
            - text-right
            - text-justify

        extraPlugins:
            - justify

        removePlugins:
            - image

        removeButtons:
            - Anchor
            - Underline
            - Strike
